// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itirwzkluaxdlvaigxtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aXJ3emtsdWF4ZGx2YWlneHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjA0MjYsImV4cCI6MjA3MDQzNjQyNn0.4QydLTc7fnrFNcQHFR8pJ8V_9netpbLEjsO9RRTPxow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});