// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clopjzpkvjyomsuanlkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsb3BqenBrdmp5b21zdWFubGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTQ5NDUsImV4cCI6MjA3MDgzMDk0NX0.GoVDBEgATloBPD03ig_5-XxxyBm6pd49oSLYwFlsYYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});